apiVersion: apps/v1 
kind: Deployment 
metadata: 
 name: test-deployment 
spec: 
 replicas: 2
 strategy: 
  type: RollingUpdate 
 selector: 
  matchLabels: 
   app: Pfe-test-front 
 template: 
   metadata: 
    labels: 
     app: Pfe-test-front
     env: prod 
   spec: 
    containers: 
    - name: test-container 
      image: ichrakmhiri1506/frontendproject:1.2
